const resource=typeof GetParentResourceName==='function'?GetParentResourceName():'traffic';
const state={routes:{},zones:{},obstacles:{},avoidance:{},mode:'normal_traffic',npc:{managed:0,repairs:0},intelligence:{},performance:{},monitor:{},adjustor:{mode:'auto',trafficLevel:70,npcLevel:70,parkedVehicleLevel:70,emergencyVehicles:true,militaryVehicles:true,population:0,reason:'Balanced server load',features:{},vehiclePolicy:{emergencyModels:[],militaryModels:[],protectedModels:[],categoryLevels:{}}},presets:[],editing:null,mloAudit:{enabled:false,findings:[],evidence:[],findingCount:0,evidenceCount:0,resourceCount:0,fileCount:0},mloPlan:null,jobRules:[],activeEvent:null,learning:{active:false,pending:false,points:0,distance:0,status:'IDLE',lastSaved:''}};
const featureLabels={traffic:'NPC Traffic Processing',population:'World Population Density',routing:'Learned Route Driving',recovery:'Stuck & Recovery System',learning:'Teach Route Learning',intelligence:'Intersection Intelligence',discovery:'Automatic Route Discovery',npcManager:'Managed NPC Spawner',appearance:'NPC Appearance Protection',performance:'Performance Governor',oneSync:'OneSync Ownership Control'};
const $=s=>document.querySelector(s);
function post(n,d={}){fetch('https://'+resource+'/'+n,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)})}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function levelName(v){v=Number(v)||0;return v<20?'Minimal':v<40?'Low':v<60?'Moderate':v<80?'Balanced':v<95?'High':'Maximum'}
function csv(v){return String(v||'').split(',').map(s=>s.trim()).filter(Boolean)}
function renderRelease(){const a=state.adjustor||{};const enabled=a.masterEnabled!==false;$('#masterEnabled').checked=enabled;$('#masterLabel').textContent=enabled?'Enabled':'Disabled';$('#releaseStatus').textContent=enabled?'READY':'SAFE OFF';$('#setupStatus').textContent=a.configured?'Configuration is saved and active.':'First-run setup has not been completed.';const d=state.diagnostics||{};$('#diagnosticsSummary').textContent=d.trafficLevel!==undefined?('Traffic '+d.trafficLevel+'% • NPC '+d.npcLevel+'% • Parked '+d.parkedVehicleLevel+'% • Master '+(d.masterEnabled!==false?'ON':'OFF')+' • Scale '+Number(d.trafficScale||0).toFixed(2)+' • Tasks '+Number(d.maxTasks||0)):'Waiting for server diagnostics.';}
function renderAdvanced(){
 const a=state.adjustor||{},vp=a.vehiclePolicy||{};$('#policyReason').textContent=a.policyReason||a.reason||'Smart Traffic';
 $('#policyStatus').textContent=state.activeEvent?'EVENT':(state.jobRules.find(r=>r.active)?'JOB':'SMART');
 const e=state.activeEvent;$('#eventStatus').textContent=e?((e.name||e.type)+' • active'): 'No active event.';
 const rules=state.jobRules||[];
 $('#jobRuleList').innerHTML=rules.map(r=>'<div class="item"><div><strong>'+esc(r.name||r.id)+'</strong><small>'+esc((r.jobs||[]).join(', '))+' • grade '+esc(r.minimumGrade||0)+' • priority '+esc(r.priority||0)+'</small></div><button data-job-rule="'+esc(r.id)+'">Delete</button></div>').join('')||'<small>No custom job rules.</small>';
 document.querySelectorAll('[data-job-rule]').forEach(b=>b.onclick=()=>post('deleteJobRule',{id:b.dataset.jobRule}));
 if(vp.emergencyModels)$('#emergencyModels').value=vp.emergencyModels.join(', ');
 if(vp.militaryModels)$('#militaryModels').value=vp.militaryModels.join(', ');
 if(vp.protectedModels)$('#protectedModels').value=vp.protectedModels.join(', ');
 document.querySelectorAll('[data-category]').forEach(i=>{const v=vp.categoryLevels&&vp.categoryLevels[i.dataset.category];i.checked=(v===undefined||Number(v)>0)});
}
function renderJobContext(){
 const ctx=state.adjustor&&state.adjustor.jobContext;
 if(ctx&&ctx.active){$('#policyStatus').textContent='JOB: '+(ctx.rule?.name||ctx.job||'ACTIVE');}
}

let adjustorEditing=false;let featureEditing=false;
function renderAdjustor(){
 const a=state.adjustor||{};const t=Number(a.trafficLevel??0),n=Number(a.npcLevel??0),p=Number(a.parkedVehicleLevel??70);
 $('#trafficLevel').textContent=t+'%';$('#npcLevel').textContent=n+'%';$('#population').textContent=a.population||0;$('#parkedValue').textContent=p+'%';
 if(!adjustorEditing){$('#trafficSlider').value=t;$('#npcSlider').value=n;$('#parkedSlider').value=p;$('#trafficValue').textContent=t+'%';$('#npcValue').textContent=n+'%';$('#parkedValue').textContent=p+'%';$('#emergencyVehicles').checked=a.emergencyVehicles!==false;$('#militaryVehicles').checked=a.militaryVehicles!==false;$('#adjustorMode').value=a.mode==='manual'?'manual':'auto';$('#trafficMode').value=ConfigTrafficMode(a.trafficMode);}$('#adjustorStatus').textContent=(a.mode||'auto').toUpperCase();
 $('#levelTitle').textContent=levelName(t)+' / '+levelName(n);$('#levelReason').textContent=a.reason||'Configured';
 $('#trafficBar').style.width=t+'%';$('#npcBar').style.width=n+'%';
}
function renderPresets(){const el=$('#presetList');if(!el)return;el.innerHTML=(state.presets||[]).map(p=>'<div class="preset"><div><strong>'+esc(p.name)+'</strong><small>'+esc(p.description||'')+'</small><span>'+esc(p.mode||'auto')+' • Traffic '+Number(p.trafficLevel||0)+'% • NPC '+Number(p.npcLevel||0)+'% • Parked '+Number(p.parkedVehicleLevel??70)+'%</span></div><div><button data-preset="'+esc(p.id)+'">Apply</button>'+(p.builtIn?'':'<button data-delete-preset="'+esc(p.id)+'">Delete</button>')+'</div></div>').join('')||'<small>No presets available.</small>';document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{featureEditing=false;post('applyPreset',{id:b.dataset.preset})});document.querySelectorAll('[data-delete-preset]').forEach(b=>b.onclick=()=>post('deletePreset',{id:b.dataset.deletePreset}))}
function renderFeatures(){
 if(featureEditing)return;
 const f=state.adjustor.features||{};
 $('#features').innerHTML=Object.keys(featureLabels).map(k=>'<label class="feature"><span><strong>'+esc(featureLabels[k])+'</strong><small>'+esc(k)+'</small></span><input type="checkbox" data-feature="'+k+'" '+(f[k]!==false?'checked':'')+'></label>').join('');
}
function renderMLOAudit(){
 const r=state.mloAudit||{},s=$('#mloSummary'),f=$('#mloFindings');if(!s||!f)return;
 const cap=r.capability||{};
 s.innerHTML=`<div class="healthGrid"><div><b>${Number(r.resourceCount||0)}</b><small>Map resources scanned</small></div><div><b>${Number(r.fileCount||0)}</b><small>Collision/map assets</small></div><div><b>${Number(r.findingCount||0)}</b><small>Duplicate findings</small></div><div><b>${Number(r.evidenceCount||0)}</b><small>Runtime evidence</small></div></div><div class="mloCapabilities"><span>Duplicate assets: ${cap.duplicateAssets?'YES':'NO'}</span><span>Runtime correlation: ${cap.runtimeCorrelation?'YES':'NO'}</span><span>Geometry overlap: ${cap.spatialGeometry?'YES':'NOT AVAILABLE'}</span><span>Destructive auto-fix: ${cap.automaticDestructiveFix?'ENABLED':'DISABLED'}</span></div>`;
 const dup=(r.findings||[]).map(x=>`<div class="item mloFinding"><div><strong>🔴 Duplicate collision asset • ${esc(x.size||0)} bytes</strong><small>${esc(x.message||'Potential duplicate asset')}<br>${x.files.map(v=>esc(v.resource)+' / '+esc(v.path)).join('<br>')}</small></div><button data-mlo-ignore="${esc(x.key)}">Ignore</button></div>`).join('');
 const evidence=(r.evidence||[]).slice(0,40).map(x=>{
  const resources=Object.keys(x.resources||{}).join(', ')||'No resource match yet';
  return `<div class="item mloFinding"><div><strong>🟠 ${esc(x.state||'suspected')} • ${esc(x.hits||0)} hits • confidence ${Number(x.confidence||0).toFixed(0)}%</strong><small>${Number(x.x||0).toFixed(1)}, ${Number(x.y||0).toFixed(1)}, ${Number(x.z||0).toFixed(1)}<br>Resources: ${esc(resources)}</small></div><button data-mlo-fix="${esc(x.id)}">Plan Safe Fix</button></div>`;
 }).join('');
 f.innerHTML=`<h3>MLO conflicts</h3>${dup||'<small>No duplicate collision assets found.</small>'}<h3>Runtime correlation</h3>${evidence||'<small>No runtime MLO evidence yet.</small>'}`;
 document.querySelectorAll('[data-mlo-ignore]').forEach(b=>b.onclick=()=>post('mloIgnore',{key:b.dataset.mloIgnore}));
 document.querySelectorAll('[data-mlo-fix]').forEach(b=>b.onclick=()=>post('mloFixPlan',{id:b.dataset.mloFix}));
}
function renderHealth(){const n=state.npc||{},i=state.intelligence||{},m=state.monitor||{};$('#health').innerHTML='<div class="healthGrid"><div><b>'+esc(n.managed||0)+'</b><small>Managed NPCs</small></div><div><b>'+esc(n.repairs||0)+'</b><small>Appearance repairs</small></div><div><b>'+esc(n.invisible||0)+'</b><small>Invisible detected</small></div><div><b>'+esc(n.mismatched||0)+'</b><small>Clothing mismatches</small></div><div><b>'+esc(i.congestion||0)+'</b><small>Congestion events</small></div><div><b>'+esc(i.gridlocks||0)+'</b><small>Gridlock releases</small></div><div><b>'+esc(m.npcVehicles||0)+'</b><small>NPC vehicles</small></div><div><b>'+esc(m.ownedVehicles||0)+'</b><small>Local network owner</small></div></div>'}
function drawHeatmap(){const c=$('#heatmap'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0a0d13';ctx.fillRect(0,0,w,h);const pts=[];Object.values(state.routes).forEach(r=>(r.points||[]).forEach(p=>pts.push({x:+p.x,y:+p.y,t:'route',v:+(r.confidence||0)})));Object.values(state.obstacles).forEach(o=>pts.push({x:+o.x,y:+o.y,t:'hot',v:+(o.hits||1)}));Object.values(state.zones).forEach(z=>pts.push({x:+z.x,y:+z.y,t:'zone',v:1}));if(!pts.length)return;const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),sx=maxX-minX||1,sy=maxY-minY||1;pts.forEach(p=>{const x=20+((p.x-minX)/sx)*(w-40),y=20+((maxY-p.y)/sy)*(h-40);ctx.beginPath();ctx.arc(x,y,p.t==='hot'?Math.min(16,4+p.v*1.5):p.t==='zone'?9:3,0,Math.PI*2);ctx.fillStyle=p.t==='hot'?'#ff6b6b':p.t==='zone'?'#f0c674':'#8aa7ff';ctx.globalAlpha=p.t==='route'?.45:.8;ctx.fill()});ctx.globalAlpha=1}
function render(){
 $('#mode').textContent=state.mode.toUpperCase();$('#routes').textContent=Object.keys(state.routes).length;$('#hotspots').textContent=Object.keys(state.obstacles).length;
 $('#routeList').innerHTML=Object.values(state.routes).sort((a,b)=>(b.confidence||0)-(a.confidence||0)).map(r=>'<div class="item"><div><strong>'+esc(r.name||r.id)+'</strong><small>'+((r.points||[]).length)+' points • confidence '+Number(r.confidence||0).toFixed(1)+' • '+Number(r.successes||0)+' successes / '+Number(r.failures||0)+' failures</small></div><div><button data-edit="'+esc(r.id)+'">Edit</button><button data-route="'+esc(r.id)+'">Delete</button></div></div>').join('')||'<small>No learned routes.</small>';
 $('#zoneList').innerHTML=Object.values(state.zones).map(z=>'<div class="item"><div><strong>'+esc(z.name||z.type||z.id)+'</strong><small>'+esc(z.type)+' • radius '+Number(z.radius||0).toFixed(0)+'</small></div><button data-zone="'+esc(z.id)+'">Delete</button></div>').join('')||'<small>No zones.</small>';
 $('#obstacleList').innerHTML=Object.values(state.obstacles).sort((a,b)=>(b.hits||0)-(a.hits||0)).slice(0,40).map(o=>'<div class="item"><div><strong>'+esc(o.category||'unknown')+' • '+esc(o.hits||0)+' hits</strong><small>'+Number(o.x).toFixed(1)+', '+Number(o.y).toFixed(1)+', '+Number(o.z).toFixed(1)+' • '+esc(o.reason||'blocked')+' • confidence '+Number(o.confidence||0).toFixed(0)+'%</small></div><button data-obstacle="'+esc(o.id)+'">Clear</button></div>').join('')||'<small>No learned hotspots yet.</small>';$('#avoidanceList').innerHTML=Object.values(state.avoidance).sort((a,b)=>(b.hits||0)-(a.hits||0)).slice(0,40).map(o=>'<div class="item"><div><strong>Route failure • '+esc(o.hits||0)+' hits</strong><small>'+Number(o.x).toFixed(1)+', '+Number(o.y).toFixed(1)+', '+Number(o.z).toFixed(1)+' • '+esc(o.reason||'route_failure')+'</small></div><button data-avoidance="'+esc(o.id)+'">Clear</button></div>').join('')||'<small>No route-failure avoidance hotspots yet.</small>';
 renderRelease();renderAdjustor();if(!featureEditing)renderFeatures();renderPresets();renderAdvanced();renderJobContext();renderHealth();renderMLOAudit();renderLearning();drawHeatmap();
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editRoute(b.dataset.edit));document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>post('deleteRoute',{id:b.dataset.route}));document.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>post('deleteZone',{id:b.dataset.zone}));document.querySelectorAll('[data-obstacle]').forEach(b=>b.onclick=()=>post('deleteObstacle',{id:b.dataset.obstacle}));document.querySelectorAll('[data-avoidance]').forEach(b=>b.onclick=()=>post('deleteAvoidance',{id:b.dataset.avoidance}));
}
function editRoute(id){const r=JSON.parse(JSON.stringify(state.routes[id]));if(!r)return;state.editing=r;$('#editor').classList.add('show');$('#routeName').value=r.name||r.id;$('#loop').checked=!!r.loop;renderPoints()}
function renderPoints(){const pts=state.editing.points||[];$('#points').innerHTML=pts.map((p,i)=>'<div class="point"><span>#'+(i+1)+'</span><input data-p="'+i+'" data-k="x" value="'+Number(p.x).toFixed(3)+'"><input data-p="'+i+'" data-k="y" value="'+Number(p.y).toFixed(3)+'"><input data-p="'+i+'" data-k="z" value="'+Number(p.z).toFixed(3)+'"><input data-p="'+i+'" data-k="heading" value="'+Number(p.heading||0).toFixed(1)+'"><button data-remove="'+i+'">×</button></div>').join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.editing.points.splice(Number(b.dataset.remove),1);renderPoints()});document.querySelectorAll('[data-p]').forEach(i=>i.onchange=()=>{state.editing.points[Number(i.dataset.p)][i.dataset.k]=Number(i.value)})}
function closeEditor(){state.editing=null;$('#editor').classList.remove('show')}
$('#save').onclick=()=>{if(!state.editing)return;state.editing.name=$('#routeName').value.trim()||state.editing.id;state.editing.loop=$('#loop').checked;post('updateRoute',{route:state.editing});closeEditor()};$('#cancel').onclick=closeEditor;$('#addPoint').onclick=()=>{const pts=state.editing.points,p=pts[pts.length-1]||{x:0,y:0,z:0,heading:0};pts.push({x:p.x,y:p.y,z:p.z,heading:p.heading});renderPoints()};
function ConfigTrafficMode(v){const modes=['normal','light','heavy','stop','emergency','race'];return modes.includes(v)?v:'normal'}
function settingsPayload(){const features={};document.querySelectorAll('[data-feature]').forEach(i=>features[i.dataset.feature]=i.checked);return {mode:$('#adjustorMode').value,trafficMode:ConfigTrafficMode($('#trafficMode').value),trafficLevel:Number($('#trafficSlider').value),npcLevel:Number($('#npcSlider').value),parkedVehicleLevel:Number($('#parkedSlider').value),emergencyVehicles:$('#emergencyVehicles').checked,militaryVehicles:$('#militaryVehicles').checked,features}}
let adjustorLiveTimer=0;
function applyAdjustorLive(forceManual=true){const p=settingsPayload();if(forceManual){p.mode='manual';$('#adjustorMode').value='manual';}state.adjustor={...state.adjustor,mode:p.mode,trafficMode:p.trafficMode,trafficLevel:p.trafficLevel,npcLevel:p.npcLevel,parkedVehicleLevel:p.parkedVehicleLevel,emergencyVehicles:p.emergencyVehicles,militaryVehicles:p.militaryVehicles,features:p.features};adjustorEditing=true;$('#adjustorStatus').textContent='APPLYING';clearTimeout(adjustorLiveTimer);adjustorLiveTimer=setTimeout(()=>{post('updateSettings',p);$('#adjustorStatus').textContent='SAVED';setTimeout(()=>{if(adjustorEditing)$('#adjustorStatus').textContent=(state.adjustor.mode||'auto').toUpperCase()},350)},120)}
function TrafficAdjustorPreview(p){state.adjustor.mode=p.mode;state.adjustor.trafficMode=p.trafficMode||state.adjustor.trafficMode||'normal';state.adjustor.trafficLevel=Number(p.trafficLevel);state.adjustor.npcLevel=Number(p.npcLevel);state.adjustor.parkedVehicleLevel=Number(p.parkedVehicleLevel??70);state.adjustor.emergencyVehicles=p.emergencyVehicles!==false;state.adjustor.militaryVehicles=p.militaryVehicles!==false;state.adjustor.features=p.features||state.adjustor.features;}
$('#applyAdjustor').onclick=()=>{const p=settingsPayload();state.adjustor={...state.adjustor,mode:p.mode,trafficMode:p.trafficMode,trafficLevel:p.trafficLevel,npcLevel:p.npcLevel,parkedVehicleLevel:p.parkedVehicleLevel,emergencyVehicles:p.emergencyVehicles,militaryVehicles:p.militaryVehicles,features:p.features};adjustorEditing=false;featureEditing=false;post('updateSettings',p);renderAdjustor();renderFeatures()};
$('#resetAdjustor').onclick=()=>{featureEditing=false;post('applyPreset',{id:'normal_traffic'})};$('#savePreset').onclick=()=>{const name=$('#presetName').value.trim();if(!name)return;const p=settingsPayload();p.id=name;p.name=name;p.description='Custom admin preset';post('savePreset',p);$('#presetName').value=''};
$('#adjustorMode').onfocus=()=>adjustorEditing=true;$('#adjustorMode').onchange=e=>{adjustorEditing=true;$('#adjustorStatus').textContent=e.target.value.toUpperCase()};$('#trafficMode').onfocus=()=>adjustorEditing=true;$('#trafficMode').onchange=()=>applyAdjustorLive(true);
$('#trafficSlider').onfocus=()=>adjustorEditing=true;$('#npcSlider').onfocus=()=>adjustorEditing=true;$('#parkedSlider').onfocus=()=>adjustorEditing=true;
$('#trafficSlider').oninput=e=>{$('#trafficValue').textContent=e.target.value+'%';$('#trafficBar').style.width=e.target.value+'%';applyAdjustorLive(true)};
$('#npcSlider').oninput=e=>{$('#npcValue').textContent=e.target.value+'%';$('#npcBar').style.width=e.target.value+'%';applyAdjustorLive(true)};$('#parkedSlider').oninput=e=>{$('#parkedValue').textContent=e.target.value+'%';applyAdjustorLive(true)};$('#emergencyVehicles').onchange=()=>applyAdjustorLive(true);$('#militaryVehicles').onchange=()=>applyAdjustorLive(true);
$('#startEvent').onclick=()=>post('startEvent',{kind:$('#eventType').value,duration:Number($('#eventDuration').value||120)*1000});$('#stopEvent').onclick=()=>post('stopEvent');$('#saveJobRule').onclick=()=>{const actions={traffic:true,npc:true,parked:true,emergency:true,military:true,events:true,zones:true};post('saveJobRule',{id:$('#jobRuleId').value,name:$('#jobRuleName').value,jobs:csv($('#jobNames').value),minimumGrade:Number($('#jobGrade').value||0),priority:Number($('#jobPriority').value||0),mode:$('#jobMode').value,trafficLevel:Number($('#jobTraffic').value||70),npcLevel:Number($('#jobNPC').value||70),parkedVehicleLevel:Number($('#jobParked').value||70),emergencyVehicles:true,militaryVehicles:true,actions});};$('#saveVehiclePolicy').onclick=()=>{const categoryLevels={};document.querySelectorAll('[data-category]').forEach(i=>categoryLevels[i.dataset.category]=i.checked?100:0);post('saveVehiclePolicy',{emergencyModels:csv($('#emergencyModels').value),militaryModels:csv($('#militaryModels').value),protectedModels:csv($('#protectedModels').value),categoryLevels});};$('#createZone').onclick=()=>post('createZone',{type:$('#zoneType').value,radius:Number($('#zoneRadius').value)||60});
function renderLearning(){const l=state.learning||{};const b=$('#teachToggle');if(b)b.textContent=l.active?'Stop & Save Route':'Start Teaching';const status=l.pending?'SAVING':(l.active?'RECORDING':(l.status||'IDLE'));$('#teachState').textContent=status.toUpperCase();$('#teachPoints').textContent=Number(l.points||0)+' points';$('#teachDistance').textContent=Number(l.distance||0).toFixed(1)+' m';$('#teachSave').textContent=l.lastSaved||'Not saved';$('#teachStatus').textContent=l.active?'Drive the intended route. Points are recorded automatically.':l.pending?'Route is being saved to the server.':(l.status||'Use /trafficteach to start recording.');}

document.addEventListener('change',e=>{if(e.target.matches('[data-feature]')){featureEditing=true;const name=e.target.dataset.feature;const enabled=e.target.checked;state.adjustor.features[name]=enabled;const p=settingsPayload();p.features={};Object.keys(featureLabels).forEach(k=>p.features[k]=state.adjustor.features[k]!==false);post('updateSettings',p);$('#adjustorStatus').textContent='SAVING';setTimeout(()=>{if(featureEditing)$('#adjustorStatus').textContent=(state.adjustor.mode||'auto').toUpperCase()},250);}});
window.addEventListener('message',e=>{if(e.data.action==='open'){document.body.classList.add('ui-open')}if(e.data.action==='jobRules'){state.jobRules=e.data.rules||[];renderAdvanced()}if(e.data.action==='trafficEvent'){state.activeEvent=e.data.event||null;renderAdvanced()}if(e.data.action==='presets'){state.presets=e.data.presets||[];renderPresets()}if(e.data.action==='open'||e.data.action==='data'){state.routes=e.data.routes||{};state.zones=e.data.zones||{};state.obstacles=e.data.obstacles||{};state.avoidance=e.data.avoidance||{};state.mode=e.data.trafficMode||e.data.mode||'normal';state.npc=e.data.npc||{};state.intelligence=e.data.intelligence||{};state.performance=e.data.performance||{};state.monitor=e.data.monitor||{};state.adjustor=e.data.adjustor||state.adjustor;state.learning=e.data.learning||state.learning;render()}if(e.data.action==='diagnostics'){state.diagnostics=e.data.snapshot||{};renderRelease()}if(e.data.action==='configExport'){const json=JSON.stringify(e.data.snapshot||{},null,2);$('#configImport').value=json;try{navigator.clipboard&&navigator.clipboard.writeText(json)}catch(_){}renderRelease()}if(e.data.action==='importResult'){alert(e.data.message||'Configuration import complete.')}if(e.data.action==='mloAudit'){state.mloAudit=e.data.report||{};renderMLOAudit()}if(e.data.action==='mloFixPlan'){state.mloPlan=e.data.plan||null;alert('Safe fix plan: '+(state.mloPlan.recommended||'Review the suspected resource before making changes.'))}});
$('#scanMLOs').onclick=()=>post('scanMLOs');$('#teachToggle').onclick=()=>post('toggleLearning');
$('#masterEnabled').onchange=e=>{post('setMasterEnabled',{enabled:e.target.checked});state.adjustor.masterEnabled=e.target.checked;renderRelease()};
$('#completeSetup').onclick=()=>post('completeSetup');
$('#refreshDiagnostics').onclick=()=>post('requestDiagnostics');
$('#exportSettings').onclick=()=>post('exportSettings');
$('#importSettings').onclick=()=>{try{const config=JSON.parse($('#configImport').value);post('importSettings',{config})}catch(e){alert('Invalid JSON configuration.')}};

window.addEventListener('message',e=>{if(e.data.action==='mode'){state.mode=e.data.mode||state.mode;render()}if(e.data.action==='learning'){state.learning=e.data.learning||state.learning;renderLearning()}});
function closeUI(){document.body.classList.remove('ui-open');post('close')}$('#close').onclick=closeUI;document.addEventListener('keydown',e=>{if(e.key==='Escape')closeUI()});
